basePath: /api/user
definitions:
  user_model.UserCreateRequest:
    properties:
      email:
        description: email
        type: string
      name:
        description: name
        type: string
      password:
        description: password
        type: string
      type:
        allOf:
        - $ref: '#/definitions/user_model.UserType'
        description: 使用者類型 (一般使用者, 管理者)
    required:
    - email
    - name
    - password
    - type
    type: object
  user_model.UserCreateResponse:
    properties:
      data:
        description: user id (uid in this system)
        type: string
      message:
        description: error message
        type: string
      result:
        description: 'true: success, false: error'
        type: boolean
    type: object
  user_model.UserType:
    enum:
    - normal
    - admin
    type: string
    x-enum-comments:
      Normal: 一般使用者
    x-enum-varnames:
    - Normal
    - Admin
host: 127.0.0.1:8080
info:
  contact:
    name: Leon Lin
  description: this the user service for meal order system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: meal order user API
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: create an user account, who can log in by username and password
      parameters:
      - description: body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user_model.UserCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_model.UserCreateResponse'
      summary: create user api (should be admin now)
      tags:
      - user
swagger: "2.0"
