import { Inter } from 'next/font/google'
import './globals.css'
import { FilterProvider} from './store/filterContext'
import { UserProvider } from './store/userContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MealOrder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <FilterProvider>
            {children}
          </FilterProvider>
        </UserProvider>
      </body>
    </html>
  )
}
